### ISSUE TITLE
C and C++ difference

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#10]
In Python translation, it states that 

> You've mainly been taught C++, but you're probably aware of C as a subset of C++ without classes, which is a good mental model. Your programs (lexer, parser and compiler) will never be given code that has different parsing or execution semantics under C and C++ (so, for example, I won't give you code that uses class as an identifier).

Is it still the case regarding the C-compiler?

As there is huge difference regarding the enum key word, I am not sure what supposed to be implemented.

**Comment by ymherklotz** [comment]
You should just be implementing C90, and should not look at C++ at all. This paragraph is just there in case you did not know about C, and compares it to C++, describing C as basically being C++ without classes.

Therefore, with regards to the `enum` keyword, it should just be the C implementation and not the `enum class` as in C++.

`struct` will also need typedefs if one wants to support referring to them directly, as they are in a [different namespace](http://port70.net/~nsz/c/c89/c89-draft.html#3.1.2.3) when declared in C90 which is not needed in C++:

```c
struct Foo { ... };
typedef struct Foo Foo;
```
