### ISSUE TITLE
C90 mixing declarations and statements

### ISSUE THREAD

**Issue by niklaskuusisto** [LangProc/langproc-2018-cw#12]
In C90 all declarations have to be made at the beginning of the scope, 
e.g.:

{ for(int i;...) } is invalid
{ int i; for(i;...) } is valid

and

{ int x = 1; x = 2; int y = 1; } is invalid
{ int x = 1; int y = 1; x = 2; } is valid

Making sure this is what the compiler should implement?

**Comment by ymherklotz** [comment]
Yes, the compiler should be implementing ANSI C90. A good way to check if the code you are inputting to your compiler is ANSI C90 compliant, is to run it through gcc with the following flags:

    gcc -std=c90 -ansi -pedantic -o main main.c

It will output warnings if there are bits in your code that are not in the ANSI C90 spec, which means you will not have to implement them.

**Comment by johnwickerson** [comment]
And further to what Yann said: I can confirm that none of the test cases contain `for(int i...` etc.
