### ISSUE TITLE
Testbench

### ISSUE THREAD

**Issue by lhl2617** [LangProc/langproc-2018-cw#13]
Just to confirm, only the test_deliverable component is marked as a testbench, and other testbenches we use for ourselves are not required and marked; is that correct?

**Comment by johnwickerson** [comment]
I don't understand which bit of [the spec](https://github.com/LangProc/langproc-2018-cw/blob/master/c_test_suite.md) is not clear. Could you clarify your misunderstanding?

**Comment by lhl2617** [comment]
Ideally we would use a translator testbench to make sure the python translator is working, this is not required by the spec, right?

**Comment by johnwickerson** [comment]
Correct. But note that there are some (C,Python) programs in https://github.com/LangProc/langproc-2018-cw/tree/master/c_translator/formative that you might find handy for testing your translator.
