### ISSUE TITLE
extent of feature support

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#14]
Supporting many features is time-consuming, in order to spend time wisely as the management part requires. I would like to ask should we support features to its full extent?

For example,

1. multidimensional array?
 `int a[10][10][10][10];`

2. pointer to pointer?
`int***** a;`

3. Function calls using other types?
`int f( double d, char c, float a, int* b);`

4. Function return type other than int?
`int* f(int a);`

5. Array of other types?
`double d[10];`

I also want to ask the scope of support of "arithmetic and logical expressions". Do we need to support all of them or just the ones mentioned in python?  (eg, / % ^)

As there is no mention of assignment operators other than '=' (eg, +=,-=,*=), increment operator(++,--) and cast operator, can I confirm they do not need to be supported.

Also,
6. declarator list?
`int a={1},b[10],c;`

7. Extern keyword?
`extern int i;`

**Comment by ymherklotz** [comment]
I am not sure to what extent all these features will be tested, but as these are not mentioned I would definitely not make them a high priority. I would first focus on implementing all the constructs that are in the lists that @johnwickerson added to the readme, and only if you are done with those you could think about how to handle multidimensional arrays.

However, if you have a good AST structure, these extensions should be fairly quick. If I had to guess, I would say that functions taking and returning different types will be tested, as that is part of handling those types which is in the list, as well as arrays of different types. I believe that if pointers are implemented correctly, then pointers of pointers should also just work?

About the operators, I believe that those should all be handled, but I am not sure. For things like `x += 1` they don't have to be handled directly in your AST, instead you could create a `x = x + 1` AST node which would be equivalent.

`extern` I don't think has to be handled, but declarator lists may have to be.

**Comment by johnwickerson** [comment]
Further to Yann's comments: yes these are indeed all things that could be tested (except `extern`).  My intention with "arithmetic and logical operators" was to refer to *all* of these operators, *including* things like `++` or `+=` (since these are simply a special kind of arithmetic operator that has a side-effect).
