### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#16]
I have several questions regarding the test suite.

1. Should each pair of test case files in a separate folder or just many files in the test_cases folder?
<img width="376" alt="image" src="https://user-images.githubusercontent.com/4344894/53702282-2e0af100-3dfd-11e9-94e9-275f58047040.png">
A
<img width="376" alt="image" src="https://user-images.githubusercontent.com/4344894/53702300-58f54500-3dfd-11e9-89da-ee979c934508.png">
B

2. What should be the file name of automated system and where should it be? Under the root folder or in test_cases folder?

3. Should the automated system generate any output or files?

In general, does the test suite need to follow strict requirements in order to pass an automated test system, or it just need to do its job in a reasonable way?

**Comment by johnwickerson** [comment]
The test suite doesn’t have strict requirements. It will be marked manually. So any of your options above are fine.
