### ISSUE TITLE
c_translator/formative/f7 does seem to process the global variable correctly

### ISSUE THREAD

**Issue by olly-larkin** [LangProc/langproc-2018-cw#18]
In the c_translator_templates.md file you specify that 
```C
int x;

int f(){
    return x+10;
}
```

```python
x=0

def f():
    global x
    return x+10
```

However f7.py doesn't follow this... is this a mistake?

**Comment by ymherklotz** [comment]
Yes, I believe that you are right and that the `global` keyword should be added. Otherwise it does not change the global `x` but creates a local `x`.
