### ISSUE TITLE
c_translator/formative/f9.c Using Unsupported Operator

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#21]
In line 5 of [f9.c](https://github.com/LangProc/langproc-2018-cw/blob/master/c_translator/formative/f9.c)
`if(a>b){`

The greater than operator `>` is not included in [`c_translator_templates.md`](https://github.com/LangProc/langproc-2018-cw/blob/master/c_translator_templates.md)

> Comparison operations: <,==

Is it a typo or the spec is just giving examples of comparison operations and we need to implement all of them?

**Comment by ymherklotz** [comment]
I think that it is just an example, and that all of them should be implemented. If you look in [f9.c](https://github.com/LangProc/langproc-2018-cw/blob/master/c_translator/formative/f9.c) there are examples of < and >.

**Comment by johnwickerson** [comment]
I've now fixed f9.c (and f9.py) so that `>` doesn't get used. See https://github.com/LangProc/langproc-2018-cw/commit/057f9a8556926738789ba338aadd0f60a0192d16.
