### ISSUE TITLE
Support Comments?

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#22]
There are some comments in [f8.c](https://github.com/LangProc/langproc-2018-cw/blob/master/c_translator/formative/f8.c). Are they for explanation purpose or our compiler/translator need to deal with comments? (ISO C90 doesn't accept comments in this style though)

**Comment by johnwickerson** [comment]
They were intended just for explanation. Your compiler/translator does not need to support comments. I'll remove them, in the interests of clarity.
