### ISSUE TITLE
FOR_N test

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#24]
I don't quite understand 

> FOR_N: Check that a for loop can execute more than once. _Note that due to this not being updated, this was ambiguous for a long time. This test will be special-cased, and checked manually to see whether it is testing for for or while loops, and assessed appropriately.

Is it a test for for loop or while loop, or we need to include both tests in the same file FOR_N.c?

**Comment by johnwickerson** [comment]
Sorry for the ambiguity. Fixed now. https://github.com/LangProc/langproc-2018-cw/commit/c26f9b45012f5361b65a40ed493da100771c9bd5
