### ISSUE TITLE
Ternary conditional

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#27]
Is the Ternary conditional operator in the spec?

`a= 0? a=1 : 0`

> conditional_expression : logical_or_expression '?' expression ':' conditional_expression

**Comment by johnwickerson** [comment]
For the C/Python task or the C/MIPS task?

**Comment by liqinyang** [comment]
C/MIPS task

**Comment by johnwickerson** [comment]
Yes, it comes under "arithmetic and logical expressions"
