### ISSUE TITLE
Short circuiting

### ISSUE THREAD

**Issue by lhl2617** [LangProc/langproc-2018-cw#29]
Will there be a test case testing short-circuiting in and-expressions?

e.g. 

```
int* a = NULL;
if (a != NULL && *a == 3) {
  return 0;
}
```

In normal cases, during runtime, the int pointer `a` should not be dereferenced if `a` is a null pointer; however, complications arise if short-circuiting is not implemented (i.e. Segmentation fault)

**Comment by johnwickerson** [comment]
This comes under "arithmetic and logical expressions", so *could* be tested.
