### ISSUE TITLE
Which C features in Deliverable 3?

### ISSUE THREAD

**Issue by lhl2617** [LangProc/langproc-2018-cw#3]
In [Deliverable 3](https://github.com/LangProc/langproc-2018-cw/blob/master/c_compiler.md) it is stated that 
> The input format is the same as for the translator (pre-processed C90).

Does this mean that we are only required to translate constructs defined in [c_translator_templates](https://github.com/LangProc/langproc-2018-cw/blob/master/c_translator_templates.md)? 

Will extra features be tested/marked?

**Comment by ymherklotz** [comment]
I believe that the only required features are the one defined in [c_translator_templates](https://github.com/LangProc/langproc-2018-cw/blob/master/c_translator_templates.md). I am not sure if any other features will be tested, I will ask @johnwickerson as soon as he is back.
