### ISSUE TITLE
Function Overloads

### ISSUE THREAD

**Issue by QFSW** [LangProc/langproc-2018-cw#36]
Do we need to support overloading functions?
Such as 
```c
int multiply(int a, int b) { return a * b; }
double multiply(double a, double b) { return a * b; }
```

In a similar vein, what about default parameters?

**Comment by ymherklotz** [comment]
No, both are not valid C90.

```c
$ gcc -std=c90 -ansi -pedantic -o main main.c                                                                                                                                                                                           
main.c:2:8: error: conflicting types for ‘multiply’
```

**Comment by QFSW** [comment]
Thanks, so functions must be completely unique by name in C90?

**Comment by ymherklotz** [comment]
Yes, function overloading does not exist in C, and only exists in C++. For example: https://stackoverflow.com/questions/479207/how-to-achieve-function-overloading-in-c/25026358#25026358
