### ISSUE TITLE
CRLF issues

### ISSUE THREAD

**Issue by lhl2617** [LangProc/langproc-2018-cw#48]
When I clone the repo on a windows system (even under vagrant), all newlines are converted to CRLF; I was wondering if the test environment (if it is Windows) has
```
git config --global core.autocrlf false
```
configured, or do we need to include `dos2unix` code in our shell scripts?

If in any case this causes any issues, will we get penalized for CRLF-caused issues?

**Comment by johnwickerson** [comment]
I’m not planning on testing from windows.
