### ISSUE TITLE
Shadowing variable

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#6]
In python translation, we don't need to support shadowing variable. Do we need to support it in the compiler?

> Note that for C to python translation you are not required to deal with shadowing of local variables, because Python does not have the notion of nested local scopes. So for example this:
> 
> ```
> {
>     int x;
>     {
>         int x;
>     }
> }
> ```
> does not need to be translated.

**Comment by BenShen98** [comment]
I think yes.

Under [c_compiler](https://github.com/LangProc/langproc-2018-cw/blob/master/c_compiler.md), it meationed "locally scoped variable declarations"
>Here is a list of more advanced features like you might like to implement once the basic and intermediate features are working.
>[more text]
>locally scoped variable declarations (e.g. a variable that is declared inside the body of a while loop, such as `while(...) { int x = ...; ... }`.

So I can't see reason to not include it.

**Comment by ymherklotz** [comment]
Yes, I believe as @BenShen98 mentioned it is included in the list of features that @johnwickerson added in the README for the compiler.
