### ISSUE TITLE
Travis CI advice?

### ISSUE THREAD

**Issue by lhl2617** [LangProc/langproc-2018-cw#7]
My team wants to try out Travis CI to make sure our master branch passes building and tests, however only the repo owner can have rights to enable the hook, is there any option that we could get it set up? (A collaborator can configure Travis). We could potentially use our own private repo, but that'd be non-ideal.

**Comment by ymherklotz** [comment]
How come using a personal private repo is non-ideal? I would probably opt for that, it means you have complete control over the repository. You can then periodically push commits that you know are passing to the repo in the Organisation. 

I do not think I have access to any repositories here so you would have to ask @johnwickerson.

**Comment by lhl2617** [comment]
@ymherklotz using Travis on the repo ensures that the hash we submit passes tests we configured

**Comment by ymherklotz** [comment]
You can still ensure that. The hashes in your private repository and repository in the organisation will be the same. So if you submit a hash, you just have to check in your private repository if that hash passed the travis tests.

The only disadvantage is that you will not see the travis tick on the organisation repo, just on your private one. The hashes will always be the same though.

**Comment by lhl2617** [comment]
Oh yes, totally overlooked that. Thank you.
