### ISSUE TITLE
Load Delay Slot

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#9]
The MIPS 1 architecture has a load delay slot.
The instruction immediately after lw cannot use the destination register of lw.
A nop need to be added in the assembly.
```
lw $2,0($sp)
nop
addiu $2,$2,2
```
This is no longer the case in the following architecture, as the gcc compiler don't do it unless you explicitly use '-mips1' to compile.

Do we need to consider the load delay slot?
Which MIPS architecture are we targeting?

**Comment by ymherklotz** [comment]
I believe, at least when we were making the compiler, that we did have to consider the delay slot. It should not hurt to add the `nop` instruction anyways though, as that means it will be correct for MIPS1 and possibly other MIPS architectures.

It does say in the [README](https://github.com/LangProc/langproc-2018-cw/blob/master/c_compiler.md) that the target architecture is MIPS1, so I would say that means taking into account the delay slot and other MIPS1 specific features.
